language: php

# Versions of PHP you want your project run with.

php:

 - 5.5

 - 5.6

 - 7.0


# Commands to be run before your environment runs.

before_script:

 - composer self-update

 - composer install --no-interaction

# Commands you want to run that will verify your build.

script:
 - ls
 - ls -l mvc/
 - vendor/bin/phpunit --bootstrap vendor/autoload.php mvc/tests
 #- vendor/bin/phpunit mvc/tests
